services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="http://127.0.0.1:5500"
      - http.cors.allow-credentials=true
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/var/www/html/index.html:ro
